# Generated by Django 4.2.1 on 2023-05-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='active_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='UnsubscribedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.BooleanField(default=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.subscribe')),
            ],
        ),
    ]
