# Generated by Django 4.2.1 on 2023-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_subscribe_active_user_alter_subscribe_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='active_user',
            field=models.BooleanField(),
        ),
    ]
