# Generated by Django 4.2.1 on 2023-05-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_subscribe_active_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='active_user',
        ),
    ]
