# Generated by Django 4.2.1 on 2023-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_subscribe_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
