# Generated by Django 4.2.1 on 2023-05-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_subscribe_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unsubscribeduser',
            name='inactive',
        ),
        migrations.AddField(
            model_name='unsubscribeduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
