# Generated by Django 4.2.1 on 2023-05-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='article_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='text_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unsubscribeduser',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subscribe'),
        ),
    ]
